language: android
dist: trusty
android:
    components:
        - tools
        - platform-tools
        - android-28
    licenses:
        - 'android-sdk-preview-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

script:
- ./gradlew build jacocoTestReport
- ./gradlew connectedCheck

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
  - develop
