language: android

before_install:
- yes | sdkmanager --licenses
- yes | sdkmanager --update

script:
- ./gradlew build jacocoTestReport
- ./gradlew connectedCheck

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
  - develop
