language: android
dist: trusty

script:
- ./gradlew build jacocoTestReport
- ./gradlew connectedCheck

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
  - develop
