name: Release Plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version of the target release"
        required: true

jobs:
  publish-plugin:
    name: Publish plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17

      # # - name: Gradle wrapper validation
      # #   uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: ./.github/actions/gradle-github-publish
        with:
          publishing-directory: "releases"
          publishing-project-name: "notify"
          publishing-project-description: "Simplified notification construction and delivery for Android."
          publishing-project-url: "https://github.com/karn/notify"
          publishing-artifact-group: "io.karn"
          publishing-artifact-id: "notify"
          publishing-artifact-version: "${{ inputs.version }}"
